# Generated by Django 4.0.5 on 2022-06-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_voiture', models.IntegerField()),
                ('prix', models.FloatField(max_length=56)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modele', models.CharField(max_length=56)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voitures')),
                ('annee', models.IntegerField()),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('id_acheteur', models.IntegerField()),
                ('id_marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdd.marque')),
                ('prix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.prix')),
            ],
        ),
    ]
