# Generated by Django 4.0.5 on 2022-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=56)),
                ('prenom', models.CharField(max_length=56)),
                ('email', models.CharField(max_length=56)),
                ('no_tel', models.CharField(max_length=56)),
                ('ville', models.CharField(max_length=56)),
                ('rue', models.CharField(max_length=56)),
                ('code_postale', models.CharField(max_length=56)),
            ],
        ),
    ]
