# Generated by Django 4.0.5 on 2022-06-22 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdd', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, default='2022-06-21', verbose_name="Date d'inscription"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_mise_a_jour',
            field=models.DateField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='no_tel',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='veuillez entrer un numéro de téléphone valide.', regex='[0-9]{10}')]),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='date_entree',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'entrée au catalogue"),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='prix',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.AddField(
            model_name='commande',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.employee'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id_acheteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='bdd.employee'),
        ),
    ]
