# Generated by Django 4.0.5 on 2022-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0003_commande_employee_client_date_inscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='id_acheteur',
            new_name='pk_acheteur',
        ),
    ]
