# Generated by Django 4.0.5 on 2022-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_alter_prix_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_prenom',
            new_name='prenom',
        ),
    ]
