# Generated by Django 4.0.5 on 2022-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0007_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
