# Generated by Django 4.0.5 on 2022-06-22 17:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0008_alter_marque_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code_postale',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_tel',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='veuillez entrer un numéro de téléphone valide.', regex='[0-9]{10}')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='rue',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='employee',
            name='ville',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de validation de la commande'),
            preserve_default=False,
        ),
    ]
