# Generated by Django 4.0.5 on 2022-06-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0009_employee_code_postale_employee_no_tel_employee_rue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_voiture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bdd.voiture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id_marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdd.marque'),
        ),
    ]
